# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-latex}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Geoff Jacobsen}]
  s.date = %q{2011-07-03}
  s.description = %q{rails-latex is a renderer for rails 3 which allows tex files with erb to be turned into an inline pdf.}
  s.email = %q{geoffjacobsen@gmail.com}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "lib/erb_latex.rb",
    "lib/latex_to_pdf.rb",
    "lib/rails-latex.rb",
    "test/helper.rb",
    "test/test_doc.tex",
    "test/test_latex_to_pdf.rb",
    "test/tmp/out.pdf",
    "test/tmp/rails-latex/input.log",
    "test/tmp/tmp/rails-latex/2368-1556906997793729431/input.tex",
    "test/tmp/tmp/rails-latex/4963-4557295006018958261/input.tex",
    "test/tmp/tmp/rails-latex/4982--3721012929416963247/input.aux",
    "test/tmp/tmp/rails-latex/4982--3721012929416963247/input.log",
    "test/tmp/tmp/rails-latex/4982--3721012929416963247/input.pdf",
    "test/tmp/tmp/rails-latex/4982--3721012929416963247/input.tex",
    "test/tmp/tmp/rails-latex/5267--740595184139431260/input.aux",
    "test/tmp/tmp/rails-latex/5267--740595184139431260/input.log",
    "test/tmp/tmp/rails-latex/5267--740595184139431260/input.pdf",
    "test/tmp/tmp/rails-latex/5267--740595184139431260/input.tex",
    "test/tmp/tmp/rails-latex/5710--3333891790396452158/input.aux",
    "test/tmp/tmp/rails-latex/5710--3333891790396452158/input.log",
    "test/tmp/tmp/rails-latex/5710--3333891790396452158/input.pdf",
    "test/tmp/tmp/rails-latex/5710--3333891790396452158/input.tex",
    "test/tmp/tmp/rails-latex/5773--2586044705503359975/input.aux",
    "test/tmp/tmp/rails-latex/5773--2586044705503359975/input.log",
    "test/tmp/tmp/rails-latex/5773--2586044705503359975/input.pdf",
    "test/tmp/tmp/rails-latex/5773--2586044705503359975/input.tex",
    "test/tmp/tmp/rails-latex/5808--4120984604975193544/input.tex",
    "test/tmp/tmp/rails-latex/5853--3414610511282325977/input.aux",
    "test/tmp/tmp/rails-latex/5853--3414610511282325977/input.log",
    "test/tmp/tmp/rails-latex/5853--3414610511282325977/input.pdf",
    "test/tmp/tmp/rails-latex/5853--3414610511282325977/input.tex",
    "test/tmp/tmp/rails-latex/5890--1546682180516809420/input.aux",
    "test/tmp/tmp/rails-latex/5890--1546682180516809420/input.log",
    "test/tmp/tmp/rails-latex/5890--1546682180516809420/input.pdf",
    "test/tmp/tmp/rails-latex/5890--1546682180516809420/input.tex",
    "test/tmp/tmp/rails-latex/input.log"
  ]
  s.rdoc_options = [%q{--main=README.rdoc}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.3}
  s.summary = %q{A LaTeX to pdf rails 3 renderer.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
  end
end

