---
name: Basic test suite

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.4'
          - '3.3'
          - '3.2'

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y texlive texlive-xetex poppler-utils

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
